name: Generate Daily News Digest

on:
  schedule:
    # Run every day at 7:00 AM UTC (adjust to your timezone)
    - cron: '0 7 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write  # Needed to push generated files

jobs:
  generate-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync

      - name: Generate news digest
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: uv run generate-digest

      - name: Commit and push generated digest
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Update daily digest - $(date +'%Y-%m-%d')" && git push)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
